/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { PathwayWhereInput } from "./PathwayWhereInput";
import { Type } from "class-transformer";
import { PathwayOrderByInput } from "./PathwayOrderByInput";

@ArgsType()
class PathwayFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => PathwayWhereInput,
  })
  @Field(() => PathwayWhereInput, { nullable: true })
  @Type(() => PathwayWhereInput)
  where?: PathwayWhereInput;

  @ApiProperty({
    required: false,
    type: PathwayOrderByInput,
  })
  @Field(() => PathwayOrderByInput, { nullable: true })
  @Type(() => PathwayOrderByInput)
  orderBy?: PathwayOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { PathwayFindManyArgs };
