/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreatePathwayArgs } from "./CreatePathwayArgs";
import { UpdatePathwayArgs } from "./UpdatePathwayArgs";
import { DeletePathwayArgs } from "./DeletePathwayArgs";
import { PathwayFindManyArgs } from "./PathwayFindManyArgs";
import { PathwayFindUniqueArgs } from "./PathwayFindUniqueArgs";
import { Pathway } from "./Pathway";
import { User } from "../../user/base/User";
import { PathwayService } from "../pathway.service";

@graphql.Resolver(() => Pathway)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class PathwayResolverBase {
  constructor(
    protected readonly service: PathwayService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Pathway",
    action: "read",
    possession: "any",
  })
  async _pathwaysMeta(
    @graphql.Args() args: PathwayFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Pathway])
  @nestAccessControl.UseRoles({
    resource: "Pathway",
    action: "read",
    possession: "any",
  })
  async pathways(
    @graphql.Args() args: PathwayFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Pathway[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Pathway",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Pathway, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Pathway",
    action: "read",
    possession: "own",
  })
  async pathway(
    @graphql.Args() args: PathwayFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Pathway | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Pathway",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Pathway)
  @nestAccessControl.UseRoles({
    resource: "Pathway",
    action: "create",
    possession: "any",
  })
  async createPathway(
    @graphql.Args() args: CreatePathwayArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Pathway> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Pathway",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Pathway"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        owner: {
          connect: args.data.owner,
        },
      },
    });
  }

  @graphql.Mutation(() => Pathway)
  @nestAccessControl.UseRoles({
    resource: "Pathway",
    action: "update",
    possession: "any",
  })
  async updatePathway(
    @graphql.Args() args: UpdatePathwayArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Pathway | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Pathway",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Pathway"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          owner: {
            connect: args.data.owner,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Pathway)
  @nestAccessControl.UseRoles({
    resource: "Pathway",
    action: "delete",
    possession: "any",
  })
  async deletePathway(
    @graphql.Args() args: DeletePathwayArgs
  ): Promise<Pathway | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Pathway",
    action: "read",
    possession: "any",
  })
  async owner(
    @graphql.Parent() parent: Pathway,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getOwner(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
