/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, IsEnum, ValidateNested } from "class-validator";
import { EnumObjectObjectType } from "./EnumObjectObjectType";
import { PathwayWhereUniqueInput } from "../../pathway/base/PathwayWhereUniqueInput";
import { Type } from "class-transformer";
@InputType()
class ObjectCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: true,
    enum: EnumObjectObjectType,
  })
  @IsEnum(EnumObjectObjectType)
  @Field(() => EnumObjectObjectType)
  objectType!: "Text" | "Image" | "Video";

  @ApiProperty({
    required: false,
    type: () => PathwayWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PathwayWhereUniqueInput)
  @IsOptional()
  @Field(() => PathwayWhereUniqueInput, {
    nullable: true,
  })
  pathway?: PathwayWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  title!: string;
}
export { ObjectCreateInput };
