/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateObjectArgs } from "./CreateObjectArgs";
import { UpdateObjectArgs } from "./UpdateObjectArgs";
import { DeleteObjectArgs } from "./DeleteObjectArgs";
import { ObjectFindManyArgs } from "./ObjectFindManyArgs";
import { ObjectFindUniqueArgs } from "./ObjectFindUniqueArgs";
import { Object } from "./Object";
import { Pathway } from "../../pathway/base/Pathway";
import { ObjectService } from "../object.service";

@graphql.Resolver(() => Object)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ObjectResolverBase {
  constructor(
    protected readonly service: ObjectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "any",
  })
  async _objectsMeta(
    @graphql.Args() args: ObjectFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [Object])
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "any",
  })
  async objects(
    @graphql.Args() args: ObjectFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Object[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Object",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => Object, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "own",
  })
  async object(
    @graphql.Args() args: ObjectFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Object | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "Object",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => Object)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "create",
    possession: "any",
  })
  async createObject(
    @graphql.Args() args: CreateObjectArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Object> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "Object",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Object"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        pathway: args.data.pathway
          ? {
              connect: args.data.pathway,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Object)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async updateObject(
    @graphql.Args() args: UpdateObjectArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Object | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "Object",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"Object"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          pathway: args.data.pathway
            ? {
                connect: args.data.pathway,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Object)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "delete",
    possession: "any",
  })
  async deleteObject(
    @graphql.Args() args: DeleteObjectArgs
  ): Promise<Object | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Pathway, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "any",
  })
  async pathway(
    @graphql.Parent() parent: Object,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<Pathway | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "Pathway",
    });
    const result = await this.service.getPathway(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
