/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ObjectWhereUniqueInput } from "./ObjectWhereUniqueInput";
import { ObjectUpdateInput } from "./ObjectUpdateInput";

@ArgsType()
class UpdateObjectArgs {
  @Field(() => ObjectWhereUniqueInput, { nullable: false })
  where!: ObjectWhereUniqueInput;
  @Field(() => ObjectUpdateInput, { nullable: false })
  data!: ObjectUpdateInput;
}

export { UpdateObjectArgs };
